# Deployment do Postgre
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  replicas: 10
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:14.3
        ports: 
          - containerPort: 5432
        env: 
        - name: POSTGRES_PASSWORD
          value: "kube123"
        - name: POSTGRES_USER
          value: "kubernetes"
        - name: POSTGRES_DB
          value: "kubernetes"
        
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
  - port: 5432
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenews
spec:
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
      - name: kubenews
        image: lucascassaro/kube-news:v1
        env:
        - name: DB_PASSWORD
          value: "kube123"
        - name: DB_USERNAME
          value: "kubernetes"
        - name: DB_DATABASE
          value: "kubernetes"
        - name: DB_HOST
          value: "postgre"

---
apiVersion: v1
kind: Service
metadata:
  name: kube-news
spec:
  selector:
    app: kubenews
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
  type: LoadBalancer
